# Generated by Django 4.0.6 on 2022-08-12 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='solds',
            new_name='sold',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Pname',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='ProdInv',
        ),
    ]
