# Generated by Django 4.0.6 on 2022-08-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_solds_inventory_sold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdInv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PIName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.products')),
                ('PIpurchased', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased', to='api.inventory')),
                ('PIsold', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pisold', to='api.inventory')),
            ],
        ),
    ]
