# Generated by Django 4.0.6 on 2022-08-12 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_prodinv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='purchaseds',
            new_name='purchased',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='descriptions',
            new_name='description',
        ),
        migrations.DeleteModel(
            name='ProdInv',
        ),
    ]
